#%RAML 1.0 DataType

 type: object
 properties:
   patientId:
     type: string
    
   patientName: 
     type: string
    
   address: 
     type: string
    
   age: 
     type: string
    
   gender: 
     type: string
    
   phoneNumber: 
     type: string
      
   email: 
     type: string
    
   bloodType: 
     type: string
    
   height: 
     type: string
    
   weight: 
     type: string
    
   disease: 
     type: string
    
   comments: 
     type: string
    
   status: 
     type: string
    
   hospitalId: 
     type: string

 example: !include /examples/PostPatientDetails.raml
