#%RAML 1.0 NamedExample


  [
                  {
                  "patientId" : "P001",
                  "patientName" : "Ajay Singh",
                  "address" : "9/782,Ghaziabad,Uttar Pradesh, 201005, India",
                  "age" : "29",
                  "gender" : "male",
                  "phoneNumber" : "9827839281",
                  "email" : "ajay@gmail.com",
                  "bloodType" : "A+",
                  "height" : "173",
                  "weight" : "85",
                  "disease" : "stomachPain",
                  "comments" : "NA",
                  "status" : "admitted",
                  "hospitalId" : "H001"
                  }
                ]
