#%RAML 1.0 Trait

headers:
  client_id:
    type: string
  client_secret:
    type: string

responses:
  401:
    body:
      application/json:
        type: !include ../datatypes/common-error-response-dataType.raml
        example: !include ../examples/401-error-response-example.json
  